Repository rooka-ai/pairlegal_documentation, pull requests merged in 2024-10, with the labels that each got.

#114 chore: german translation
  pairlegal-documentation/docs/installation/index.mdx
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/AI.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/alerts.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/definition-extraction.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/external_information.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/getting_started.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/install365.mdx
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/troubleshooting.mdx
Labels: size/M, chore

#115 feat: specify rewrite
  pairlegal-documentation/docs/editing.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/editing.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/editing.md
Labels: ⬆️ enhancement, size/M

#116 chore: minor cs improvements
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/editing.md
Labels: size/XS, chore

#118 chore: bump deps
  package-lock.json
  package.json
Labels: size/XXL, chore
