Repository rooka-ai/pairlegal_documentation, pull requests merged in 2024-12, with the labels that each got.

#139 chore: drop localization
  README.md
  package-lock.json
  pairlegal-documentation/docs/security.md
  pairlegal-documentation/docusaurus.config.js
  pairlegal-documentation/i18n/cs/code.json
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-blog/options.json
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current.json
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/AI.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/alerts.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/authentication.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/definition-extraction.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/editing.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/external_information.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/getting_started.md
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/installation/index.mdx
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/installation/install365.mdx
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/installation/troubleshooting.mdx
  pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/security.md
  pairlegal-documentation/i18n/cs/docusaurus-theme-classic/footer.json
  pairlegal-documentation/i18n/cs/docusaurus-theme-classic/navbar.json
  pairlegal-documentation/i18n/de/code.json
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-blog/options.json
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current.json
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/AI.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/alerts.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/authentication.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/definition-extraction.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/editing.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/external_information.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/getting_started.md
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/index.mdx
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/install365.mdx
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/troubleshooting.mdx
  pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/security.md
  pairlegal-documentation/i18n/de/docusaurus-theme-classic/footer.json
  pairlegal-documentation/i18n/de/docusaurus-theme-classic/navbar.json
Labels: size/XXL, chore

#140 feat: add admin docs
  pairlegal-documentation/docs/administrators.mdx
  pairlegal-documentation/static/img/adminroles.png
Labels: ⬆️ enhancement, size/M, ❕low_priority

#142 feat: team admin onboarding
  pairlegal-documentation/docs/subscription.mdx
Labels: ⬆️ enhancement, size/S

#144 feat: purchaser auto added to sub
  pairlegal-documentation/docs/subscription.mdx
Labels: ⬆️ enhancement, size/XS
