Repository rooka-ai/pairlegal_documentation, pull requests merged in 2025-04, with the labels that each got.

#177 feat: add use cases section
  pairlegal-documentation/docs/features/AI.mdx
  pairlegal-documentation/docs/features/definition-extraction.mdx
  pairlegal-documentation/docs/getting_started.md
  pairlegal-documentation/docs/installation/authentication.mdx
  pairlegal-documentation/docs/installation/index.mdx
  pairlegal-documentation/docs/installation/troubleshooting.mdx
  pairlegal-documentation/docs/settings/external_services.mdx
  pairlegal-documentation/docs/settings/user_management/index.mdx
  pairlegal-documentation/docs/use_cases/ai_customization.md
  pairlegal-documentation/docs/use_cases/error_prevention.md
  pairlegal-documentation/docs/use_cases/fast_drafting.md
  pairlegal-documentation/docs/use_cases/index.mdx
  pairlegal-documentation/docs/use_cases/knowledge_reuse.md
Labels: ⬆️ enhancement, size/L

#178 feat: minor changes
  pairlegal-documentation/docs/features/snippets.mdx
  pairlegal-documentation/docs/use_cases/ai_customization.md
  pairlegal-documentation/docs/use_cases/fast_drafting.md
  pairlegal-documentation/docs/use_cases/knowledge_reuse.md
Labels: ⬆️ enhancement, size/M

#179 fix: switch video
  pairlegal-documentation/docs/use_cases/error_prevention.md
  pairlegal-documentation/docs/use_cases/fast_drafting.md
Labels: 🐞 bug, size/S

#182 feat: add upcoming features
  pairlegal-documentation/docs/use_cases/error_prevention.md
  pairlegal-documentation/docs/use_cases/fast_drafting.md
Labels: ⬆️ enhancement, size/S

#183 fix: broken link
  pairlegal-documentation/docs/installation/enterprise.mdx
Labels: 🐞 bug, size/XS

#185 fix: link xml
  pairlegal-documentation/docs/installation/enterprise.mdx
  pairlegal-documentation/docusaurus.config.js
Labels: 🐞 bug, size/XS

#189 fix: change team admin link, disable blog indexing
  pairlegal-documentation/docs/settings/external_services.mdx
  pairlegal-documentation/docusaurus.config.js
Labels: 🐞 bug, size/XS
